<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;


/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArrayOfItemsByList($itemList)
    {
        $qb = $this->createQueryBuilder('i')
            ->select('i','pc','pi','pd','pcp','pip','pdp')
            ->leftJoin('i.paramsTypeChoice', 'pc')
            ->leftJoin('pc.Param', 'pcp')
            ->leftJoin('i.paramsTypeInt', 'pi')
            ->leftJoin('pi.Param', 'pip')
            ->leftJoin('i.paramsTypeDate', 'pd')
            ->leftJoin('pd.Param', 'pdp')
            ->where('i.itemList = :itemList')
            ->setParameter('itemList', $itemList)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);

        return $qb;
    }

    public function getArrayItemById($id){
        $qb = $this->createQueryBuilder('i')
            ->select('i','pc','pi','pd','pcp','pip','pdp')
            ->leftJoin('i.paramsTypeChoice', 'pc')
            ->leftJoin('pc.Param', 'pcp')
            ->leftJoin('i.paramsTypeInt', 'pi')
            ->leftJoin('pi.Param', 'pip')
            ->leftJoin('i.paramsTypeDate', 'pd')
            ->leftJoin('pd.Param', 'pdp')
            ->where('i.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);

        return $qb;
    }
}
