<?php

namespace AppBundle\Repository;

/**
 * ParamsTypeDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamsTypeDateRepository extends \Doctrine\ORM\EntityRepository
{
}
