<?php

namespace AppBundle\Repository;

/**
 * ParamsTypeChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamsTypeChoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
