<?php

namespace AppBundle\Repository;

/**
 * ParamsTypeIntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamsTypeIntRepository extends \Doctrine\ORM\EntityRepository
{
}
