<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParamRepository extends \Doctrine\ORM\EntityRepository
{

    public function getArrayOfParamsByList($itemList)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p','pc','pi','pd')
            ->leftJoin('p.paramsTypeChoice', 'pc')
            ->leftJoin('p.paramsTypeInt', 'pi')
            ->leftJoin('p.paramsTypeDate', 'pd')
            ->where('p.itemList = :itemList')
            ->setParameter('itemList', $itemList)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);

        return $qb;
    }

}
